export const UPDATE_WIDEBAND_USER_DATA = 'UPDATE_USER_INFO_DATA'
export const UPDATE_WIDEBAND_SERV_DATA = 'UPDATE_WIDEBAND_SERV_DATA'
export const UPDATE_WIDEBAND_INFO_DATA = 'UPDATE_WIDEBAND_INFO_DATA'
export const UPDATE_WIDEBAND_CONFIRM_DATA = 'UPDATE_WIDEBAND_ADDR_DATA'